### ISSUE TITLE
PNUnexpectedDisconnectCategory stops running after awhile

### ISSUE THREAD

**Issue by 7ooL** [silvertoken/pyvivintsky#2]
It seems that the pubnub session dies after while., i've seen the error PNUnexpectedDisconnectCategory.

any suggestions on how to catch this and reestablish a connection? I need this channel to remain open non stop as I'm monitoring it for certain events and preforming actions based on events.

**Comment by 7ooL** [comment]
I think this is probably related to the session expiring. any suggestion on how to detect and renew session expiration?

**Comment by silvertoken** [comment]
Looking at this it's a pretty general disconnect error.  I never experienced this but I can't recall if I tested longer than the 20 minute session or not.  Basically this error could also just mean the network connection is down and your experiencing issues.  Normally the way I would handle this is trap the exception and try create  it again.  If it returns a unique status code we could add a standard retry mechanism.

**Comment by 7ooL** [comment]
I no longer use this library, I've moved onto HomeAssistant.

**Comment by silvertoken** [comment]
yea I figured by now someone had to improve the integration as I haven't had much time for projects.
